config/routes.rb
Rails.application.routes.draw do

  resources :labels
  get 'sessions/new'
 
  root "users#new"
  resources :tasks 
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
   
   resources :users

  end
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :dead_line, presence: true
  validates :condition, presence: true
  validates :priority, presence: true
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  
  scope :title_search, -> (search){where('title LIKE ?', "%#{search}%")}
  scope :condition_search, -> (search){where(condition: search)}
  scope :both_search, ->(search, second_search) { where('title LIKE ?', "%#{search}%").where(condition: second_search)}
  
  enum priority: { 高: 1, 中: 2, 低: 3 }
end
 

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :destroy, :update]
  before_action :check_logged_in
  def index
    @tasks = current_user.tasks.includes(:user).page(params[:page]).per(3)
    @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
    if params[:sort_expired].present?
    @tasks = @tasks.order(dead_line: :desc).page(params[:page]).per(3)
    else
    @tasks
    end

    if params[:sort_priority].present?
      @tasks = @tasks.order(priority: :asc).page(params[:page]).per(3)
      else
      @tasks
      end
    
    if params[:task].present? && params[:task][:search].present?
      if params[:task][:title].present? && params[:task][:condition].present?
        @tasks = Task.both_search(params[:task][:title], params[:task][:condition]).page(params[:page]).per(3)
      elsif params[:task][:title].present?
        @tasks = Task.title_search(params[:task][:title]).page(params[:page]).per(3)
      elsif params[:task][:condition].present?
        @tasks = Task.condition_search(params[:task][:condition]).page(params[:page]).per(3)
      end
    end
  end
  
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to tasks_path, notice: t('view.create_task')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: t('view.update_task')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t('view.delete_task')
  end

  

  private

  def task_params
    params.require(:task).permit(:title, :content, :dead_line, :condition, 
                                 :priority, :author, :sort_expired, :search,
                                 :sort_priority, :page, { label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def check_logged_in
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def button_text
    if action_name == "new"
      t('helpers.submit.create')
    elsif action_name == "edit"
      t('helpers.submit.update')
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
    <h2><%= @task.errors.count %>件のエラーがあります</h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div class="task-title">
    <%= form.label t('view.task_title') %>
    <%= form.text_field :title, id: 'title_new' %>
  </div>
  　
  <div class="task-title">
  <%= form.label t('view.task_content') %>
  <%= form.text_field :content, id: 'content_new' %>
  </div>

  <div class="task-title">
    <%= form.label t('view.dead_line') %>
    <%= form.date_select :dead_line, {}, class: 'form-control', id: 'date_new' %>
  </div>

  <div class="task-title">
    <%= form.label t('view.condition') %>
    <%= form.select :condition, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]], include_blank: "選択して下さい" %>
  </div>

  <div class="task-title">
    <%= form.label t('view.priority') %>
    <%= form.select :priority, Task.priorities.keys.to_a, include_blank: true %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>

  <%= form.submit button_text %>
<% end %>


<% link_to t('view.go_tasks_path'), tasks_path %>
<%= link_to "新しくラベルを作成する", new_label_path %>

app/views/tasks/edit.html.erb
<h2>タスクを編集する</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>


<table>

<%= form_with(model: Task.new, method: :get, url: tasks_path, local: true) do |f| %>

 <%= f.label :title_search, "タイトル検索" %>
 <%= f.text_field :title, id: 'title_search' %>

 <%= f.label :condition_search, "状態検索" %>
 
  <%= f.select :condition, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]], 
    include_blank: true, selected: '', id: 'task_condition', class: 'form-control' %>

 <%= f.hidden_field :search, value: 'true' %>
 <%= f.submit '検索', id: 'submit' %>
<% end %>
</table>
<table class="table">

 <tr>
   <th scope="col">タスク名</th>
   <th scope="col">タスク詳細</th>
   <th scope="col">終了期限</th>
   <th scope="col">状態</th>
   <th scope="col">優先順位</th>
  </tr>
    
   <% @tasks.each do |task| %>

  <tr scope="row">
      <td class="title_row"><%= task.title %></td>
      <td><%= task.content %></td>
      <td class="date_row"><%= task.dead_line %></td>
      <td><%= task.condition %></td>
      <td class="priority_row"><%= task.priority %></td>
      
      <td><span class="label label-primary"><%= link_to t('view.show'), task_path(task.id), class: "show_link letter" %></span></td>
      <td><span class="label label-success"><%= link_to t('view.edit'), edit_task_path(task.id), class: "letter" %></span></td>
      <td><span class="label label-danger"><%= link_to t('view.delete'), task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか?'}, class: "letter" %></span></td>
      <td>
      <% task.labels.each do |label| %>
        <%= label.name %>
      <% end %>
      </td>
  </tr>
    <% end %> 
</table>
<%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
  <%= form.submit 'Search', name: nil, id: "label_submit" %>
<% end %>
<%= paginate @tasks %>
<%= link_to t('view.go_new_task_path'), new_task_path %>
<%= link_to t('view.go_sort_expired'), tasks_path(sort_expired: "true"), id: 'sort' %>
<%= link_to t('view.go_sort_priority'), tasks_path(sort_priority: "true"), id: 'sort_priority' %>
<%= link_to "新しくラベルを作成する", new_label_path %>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>タスク名:<%= @task.title %></p>
<p>タスク詳細:<%= @task.content %></p>
<p>終了期限:<%= @task.dead_line %></p>
<p>状態:<%= @task.condition %></p>
<p>優先順位:<%= @task.priority %></p>

<p>ラベル:
<% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %>
</p>