config/routes.rb
Rails.application.routes.draw do

  resources :labels
  get 'sessions/new'
 
  root "users#new"
  resources :tasks 
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
   
   resources :users

  end
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
    include SessionsHelper
    has_many :tasks, dependent: :destroy
    validates :email, uniqueness: true
    has_secure_password
    before_destroy :ensure_has_admin
    private
    
    def ensure_has_admin
      if self.admin?
        if User.count == 1
          throw(:abort) 
        end
      end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  include SessionsHelper
    before_action :admin_user
    before_action :set_user, only: [:show, :edit, :destroy, :update]

  def new
    @user = User.new
    # @user.admin = false
  end

  def create
    @user = User.new (user_params)
    # binding.irb
     if @user.save
        redirect_to admin_users_path, notice: t('view.create_task')
      else
        render :new
      end
    
  end
  def show
    @tasks = set_user.tasks.order(created_at: :desc)
    # if logged_in?
    #  if current_user.id != @user.id
    #    redirect_to tasks_path
    #  end
    # end
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
     
      redirect_to admin_users_path, notice: t('view.update_task')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: t('view.delete_user')
  end

  def index
    @users = User.all.order("created_at DESC")
  end

  private
  def admin_user
    if current_user.nil?
      redirect_to new_session_path
    elsif current_user.admin? == false
      flash[:notice] = "あなたは管理者ではありません"
      redirect_to tasks_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                        :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    if logged_in?
      redirect_to user_path(current_user)
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = current_user.tasks.order(created_at: :desc)
    if logged_in?
     if current_user.id != @user.id
       redirect_to tasks_path
     end
    end
  end
      
  private
    
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
  end
end

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account", id: "create_new" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<% if logged_in? && current_user.admin? %>
  <% if current_user.admin? %>
    <%= link_to "管理者登録画面へ", admin_user_path(@user.id), id: "admin_access" %>
  <% end %>
<% end %>
<table>
 <tr>
   <th>タスク名</th>
   <th>タスク詳細</th>
   <th>終了期限</th>
   <th>状態</th>
   <th>優先順位</th>
   <th>作者</th>
  </tr>
   <% @tasks.each do |task| %>
    <tr>
      <td><%= task.content %></td>
      <td><%= task.dead_line %></td>
      <td><%= task.condition %></td>
      <td><%= task.priority %></td>
      <td><%= task.author %></td>
      <td><%= link_to t('view.show'), task_path(task.id), class: "show_link" %></td>
      <td><%= link_to t('view.edit'), edit_task_path(task.id) %></td>
      <td><%= link_to t('view.delete'), task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか?'} %></td>
  </tr>
    <% end %> 
</table>
<%= link_to "タスク作成画面へ", new_task_path %>